influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  environment:
    INFLUXDB_ADMIN_ENABLED: "true"
  volumes:
    - ${INFLUXDB_DATA_LOCATION}:/var/lib/influxdb
  env_file:
    - .env

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
  volumes:
    - ${GRAFANA_DATA_LOCATION}:/data
    - ${PWD}/provisioning:/grafana-conf
  env_file:
    - .env
  user: "472"
